services:
  mariadb:
    container_name: "online-store-mariadb"
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=online_store'
      - 'MARIADB_PASSWORD=1234'
      - 'MARIADB_ROOT_PASSWORD=1234'
      - 'MARIADB_USER=user'
    ports:
      - '3306:3306'
    env_file:
      - .env
    restart: always
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  redis:
    image: 'redis:latest'
    container_name: 'online-store-redis'
    env_file:
      - .env
    ports:
      - '6379:6379'
    restart: always
    networks:
      - app-network
  # redis insight 추후 설치

  backend:
    container_name: "online-store-backend"
    environment:
      - DB_USER=${DB_USER}
      - DB_PW=${DB_PW}
      - PROFILES_ACTIVE=prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
      - redis
    networks:
      - app-network

  frontend:
    container_name: "online-store-frontend"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    networks:
      - app-network


networks:
  app-network:
    driver: bridge