spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mariadb://localhost:3306/online-store?allowPublicKeyRetrieval=true&useSSL=false

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect


jwt:
  secret-key: secret-key_secret-key_secret-key_secret-key.secret-key
  expired-time-ms: 3600000  # 1hour